---
### Create configuration files locally
### Must be executed only if local structure has been created with playbook: playbook-ztp-init.yml
- name: Populate local ZTP configurations
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - "group_vars/ztp-servers/ztp.yaml"
  roles:
    - {role: ztp-create-config}
